<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__react-datepicker__navigation react-datep_20a042</name>
   <tag></tag>
   <elementGuidId>7c0cfffd-5cc7-4d2f-abb0-55dbe512166b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.react-datepicker__navigation.react-datepicker__navigation--years.react-datepicker__navigation--years-previous</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dateAndTimePicker']/div[2]/div[2]/div/div/div[2]/div/div[2]/div[2]/div/div[13]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker__navigation react-datepicker__navigation--years react-datepicker__navigation--years-previous</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateAndTimePicker&quot;)/div[@class=&quot;react-datepicker__tab-loop&quot;]/div[@class=&quot;react-datepicker-popper&quot;]/div[1]/div[@class=&quot;react-datepicker&quot;]/div[@class=&quot;react-datepicker__month-container&quot;]/div[@class=&quot;react-datepicker__header&quot;]/div[@class=&quot;react-datepicker__header__dropdown react-datepicker__header__dropdown--scroll&quot;]/div[@class=&quot;react-datepicker__year-dropdown-container react-datepicker__year-dropdown-container--scroll&quot;]/div[@class=&quot;react-datepicker__year-dropdown&quot;]/div[@class=&quot;react-datepicker__year-option&quot;]/a[@class=&quot;react-datepicker__navigation react-datepicker__navigation--years react-datepicker__navigation--years-previous&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dateAndTimePicker']/div[2]/div[2]/div/div/div[2]/div/div[2]/div[2]/div/div[13]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/a</value>
   </webElementXpaths>
</WebElementEntity>
